name: Komplex
main: cz.vojtamaniak.komplex.Komplex
version: 0.1
commands:
  break:
    usage: /break
    description: Breaks the block there you looking at.
  feed:
    usage: /feed <nick>
    description: Sets as full the player's hunger bar.
  fly:
    usage: /fly <nick>
    description: Changes the player's fly mode.
  clearchat:
    usage: /clearchat
    description: Clears the chat.
  god:
    usage: /god <nick>
    description: Sets a God mode.
  hat:
    usage: /hat
    description: Sets item in player's hand as his helmet.
  heal:
    usage: /heal <nick>
    description: Heal the player.
  ptime:
    usage: /ptime set/reset/<nick> <ticks> <nick>
    description: Modify player's time.
  workbench:
    usage: /workbench
    description: Opens a crafting table to a player
  afk:
    usage: /afk
    description: Changes players afk.
  helpop:
    usage: /helpop [message]
    description: Sends a message to online admins.
  list:
    usage: /list
    description: Lists an online players.
  mail:
    usage: /mail read/send/clear <nick> <message>
    description: Mail.
  tell:
    usage: /tell [nick] [message]
    description: Send PM to a player.
  reply:
    usage: /reply [message]
    description: Reply to last received/send message.
    aliases: [r]