name: Komplex
main: cz.vojtamaniak.komplex.Komplex
version: 0.1
commands:
  break:
    usage: /break
    description: Znici blok, na ktery se divas
  feed:
    usage: /feed <nick>
    description: Doplni ti hlad.
  fly:
    usage: /fly <nick>
    description: Zapne/vypne letani.
  clearchat:
    usage: /clearchat
    description: Promaze chat.
  god:
    usage: /god <nick>
    description: Zapne/Vypne nesmrtelnost.
  hat:
    usage: /hat
    description: Da ti na hlavu blok, ktery drzis v ruce.
  heal:
    usage: /heal <nick>
    description: Vyleci hrace.
  ptime:
    usage: /ptime set/reset/<nick> <ticks> <nick>
    description: Zmeni hracuv cas.
  workbench:
    usage: /workbench
    description: Otevre crafting table.
  afk:
    usage: /afk
    description: Zapne/Vypne nepritomnost.
  helpop:
    usage: /helpop [message]
    description: Posle zpravu adminum.
  list:
    usage: /list
    description: Napise seznam online hracu.
  mail:
    usage: /mail read/send/clear <nick> <message>
    description: Maily.
  tell:
    usage: /tell [nick] [message]
    description: Posle soukromou zpravu hraci.
  reply:
    usage: /reply [message]
    description: Odpovi na posledni soukromou zpravu.
    aliases: [r]
  near:
    usage: /near <nick>
    description: Vypise hrace v okoli a vzdalenost.