name: Komplex
main: cz.vojtamaniak.komplex.Komplex
version: 0.4.4
depend: [PermissionsEx]
authors: [vojtamaniak]
commands:
  afk:
    usage: /afk
    description: Hodi hrace do AFK stavu.
  break:
    usage: /break
    description: Znici blok, na ktery se divas
  feed:
    usage: /feed {nick}
    description: Doplni ti hlad.
  fly:
    usage: /fly {nick}
    description: Zapne/vypne letani.
  clearchat:
    usage: /clearchat
    description: Promaze chat.
    aliases: [cc]
  god:
    usage: /god {nick}
    description: Zapne/Vypne nesmrtelnost.
  hat:
    usage: /hat
    description: Da ti na hlavu blok, ktery drzis v ruce.
  heal:
    usage: /heal {nick}
    description: Vyleci hrace.
  ptime:
    usage: /ptime set/reset/{nick} {ticks} {nick}
    description: Zmeni hracuv cas.
  workbench:
    usage: /workbench
    description: Otevre crafting table.
    aliases: [wb]
  helpop:
    usage: /helpop <message>
    description: Posle zpravu adminum.
  list:
    usage: /list
    description: Napise seznam online hracu.
  mail:
    usage: /mail read/send/clear <nick> <message>
    description: Maily.
  tell:
    usage: /tell <nick> <message>
    description: Posle soukromou zpravu hraci.
    aliases: [t, w]
  reply:
    usage: /reply <message>
    description: Odpovi na posledni soukromou zpravu.
    aliases: [r]
  near:
    usage: /near {nick}
    description: Vypise hrace v okoli a vzdalenost.
  ignore:
    usage: /ignore add/remove/list {nick}
    description: Ignorovani hrace/hracu
  adminchat:
    usage: /adminchat <zprava>
    description: Posle zpravu ostatnim adminum
  setwarp:
    usage: /setwarp <nazev>
    description: Nastavi warp
  warp:
    usage: /warp {nazev}
    description: Teleportne hrace na warp
  deletewarp:
    usage: /deletewarp <nazev>
    description: Smaze warp
    aliases: [delwarp]
  doublejump:
    usage: /doublejump {nick}
    description: Zapne hraci doublejump
  home:
    usage: /home {nazev}
    description: Teleportne domu.
  sethome:
    usage: /sethome {nazev}
    description: Nastavi domov.
  spawn:
    usage: /spawn {nick}
    description: Teleportuje na spawn.
  setspawn:
    usage: /setspawn
    description: Nastavi spawn.
  notices:
    usage: /notices global/add/{} {zprava}/{nick} {zprava}
    description: Notices
    aliases: [notice]
  taketicket:
    usage: /taketicket <id>
    description: Vezme ticket
  ticket:
    usage: /ticket <zprava>
    description: Vytvori ticket
  tickets:
    usage: /tickets -all/{}
    description: Vypise seznam ticketu
  closeticket:
    usage: /closeticket {id}
    description: Uzavre/otevre ticket
  editsign:
    usage: /editsign <radek> {text}
    description: Edituje sign
    aliases: [sign, signedit]
  replyticket:
    usage: /replyticket <id> <zprava>
    description: Odpovi na ticket
  deleteticket:
    usage: /deleteticket <id>
    description: Smaze ticket
    aliases: [delticket]
  checkticket:
    usage: /checkticket <id>
    description: Podiva se na ticket
  deletehome:
    usage: /deletehome {nazev}
    description: Smaze dum
    aliases: [delhome]
  vanish:
    usage: /vanish {nick}
    description: Zneviditelni hrace
  dupeip:
    usage: /dupeip <nick>/<ip>
    description: Vyuziti IP
  kick:
    usage: /kick <hrac> {duvod}
    description: Vyhodi hrace
  ban:
    usage: /ban <nick> {duvod}
    description: Zabanuje hrace
  tempban:
    usage: /tempban <nick> <pocet> <sec/min/hour/day/month/year> {duvod}
    description: Docasne zabanuje hrace
  warn:
    usage: /warn <nick> <duvod>
    description: Varuje hrace
  unban:
    usage: /unban <nick>
    description: Odbanuje hrace
  checkban:
    usage: /checkban <nick>
    description: Zjisti bany hrace
  itemid:
    usage: /itemid
    description: Zjisti id itemu
    aliases: [itemdb]
  jump:
    usage: /jump
    description: skoci
permissions:
  komplex.*:
    description: Prava na vsechny prikazy pluginu Komplex
    children:
      komplex.messages.*: true
      komplex.afk: true
      komplex.break: true
      komplex.break.bedrock: true
      komplex.clearchat: true
      komplex.feed: true
      komplex.feed.other: true
      komplex.fly: true
      komplex.fly.other: true
      komplex.god: true
      komplex.god.other: true
      komplex.hat: true
      komplex.heal: true
      komplex.heal.other: true
      komplex.helpop: true
      komplex.helpop.receive: true
      komplex.list: true
      komplex.mail: true
      komplex.near: true
      komplex.near.other: true
      komplex.ptime.get: true
      komplex.ptime.get.other: true
      komplex.ptime.reset: true
      komplex.ptime.reset.other: true
      komplex.ptime.set: true
      komplex.ptime.set.other: true
      komplex.reply: true
      komplex.tell: true
      komplex.workbench: true
      komplex.ignore: true
      komplex.ignore.bypass: true
  komplex.messages.*:
    description: Ziskavani vsech zprav z pluginu Komplex
    children:
      komplex.messages.afk: true
      komplex.messages.onjoin: true
      komplex.messages.onquit: true
  komplex.messages.afk:
    description: Ziskavani zprav o AFK
    default: true
  komplex.messages.onjoin:
    default: true
    description: Ziskavani zprav o pripojeni hracu
  komplex.messages.onquit:
    default: true
    description: Ziskavani zprav o odpojeni hracu
  komplex.afk:
    default: true
    description: Prida prava na prikaz /afk
  komplex.break:
    default: op
    description: Prida prava na prikaz /break
  komplex.break.bedrock:
    default: op
    description: Prida prava na zniceni bedrocku prikazem /break
  komplex.clearchat:
    default: op
    description: Prida prava na prikaz /clearchat
  komplex.feed:
    default: op
    description: Prida prava na prikaz /feed
  komplex.feed.other:
    default: op
    description: Prida prava na nasyceni ostatnich hracu
  komplex.fly:
    default: op
    description: Prida prava na prikaz /fly
  komplex.fly.other:
    default: op
    description: Prida prava na zapnuti letani ostatnich hracu
  komplex.god:
    default: op
    description: Prida prava na prikaz /god
  komplex.god.other:
    default: op
    description: Prida prava na zapnuti god ostatnich hracu
  komplex.hat:
    default: op
    description: Prida prava na prikaz /hat
  komplex.heal:
    default: op
    description: Prida prava na prikaz /heal
  komplex.heal.other:
    default: op
    description: Prida prava na uzdraveni ostatnich hracu
  komplex.helpop:
    default: true
    description: Prida prava na prikaz /helpop
  komplex.helpop.receive:
    default: op
    description: Prida prava na cteni /helpop zprav
  komplex.list:
    default: true
    description: Prida prava na prikaz /list
  komplex.mail:
    default: true
    description: Prida prava na prikaz /mail
  komplex.near:
    default: op
    description: Prida prava na prikaz /near
  komplex.near.other:
    default: op
    description: Prida prava na prikaz /near nick
  komplex.ptime.get:
    default: true
    description: Prida prava na ziskani vlastniho casu
  komplex.ptime.get.other:
    default: op
    description: Prida prava na ziskani casu ostatnich hracu
  komplex.ptime.reset:
    default: op
    description: Prida prava na resetovani vlastniho casu
  komplex.ptime.reset.other:
    default: op
    description: Prida prava na resetovani casu ostatnich hracu
  komplex.ptime.set:
    default: op
    description: Prida prava na nastaveni vlastniho casu
  komplex.ptime.set.other:
    default: op
    description: Prida prava na nastaveni casu ostatnich hracu
  komplex.reply:
    default: true
    description: Prida prava na prikaz /reply
  komplex.tell:
    default: true
    description: Prida prava na prikaz /tell
  komplex.workbench:
    default: op
    description: Prida prava na prikaz /workbench
  komplex.ignore:
    default: true
    description: Prida prava na prikaz /ignore
  komplex.ignore.bypass:
    default: op
    description: Zamezi hraci byt ignorovan.
  komplex.adminchat:
    default: op
    description: Prida prava na prikaz /adminchat a na prijmani adminchatovych zprav
  komplex.setwarp:
    default: op
    description: Prida prava na prikaz /setwarp
  komplex.deletewarp:
    default: op
    description: Prida prava na prikaz /deletewarp
  komplex.warp:
    default: true
    description: Prida prava na prikaz /warp
